name: General Tests

on: [push, pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: ./frontend

  general-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env for tests
        run: cp .env.example .env

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry
      
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('backend/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        working-directory: ./backend

      - name: Run tests
        run: poetry run pytest tests/general_tests -v
        working-directory: ./backend

  integration-tests:
    needs: general-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env for tests
        run: cp .env.example .env

      - name: Start containers
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d --build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry
      
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('backend/poetry.lock') }}

      - name: Install dependencies
        run: poetry install
        working-directory: ./backend

      - name: Run integration tests
        run: poetry run pytest tests/integration_tests -v
        working-directory: ./backend

      - name: Stop containers
        if: always()
        run: |
          echo "----- All container logs -----"
          docker compose -f docker-compose.yml -f docker-compose.test.yml logs
          docker compose -f docker-compose.yml -f docker-compose.test.yml down
